#!/bin/bash

# RECEBER TOKENS NO SEU BOT DO TELEGRAM
TOKEN=SEUTOKEN
ID=SEUID

clear

if [ -f tokens ]; then
     echo
else 
   > tokens
fi

echo -e "\e[01;33mBUSCANDO NOVOS TOKENS\e[0m\n"
while :; do
      
      new=$(curl -s https://tokensniffer.com/tokens/new | pup '#__NEXT_DATA__' | sed '2q;d' | jq -r '.props.pageProps.tokens."0"[],.props.pageProps.tokens."1"[] | {name:.name,addr:.addr}' | jq .name,.addr -r | tr -d ' ' > tokens2)
      new2=$(diff tokens tokens2 | grep '>' | tr -d '> ')
      new3=$(wc -l <<< $new2)
             case $new3 in
                   1) echo -e "\e[01;33mProcurando...\e[0m"
                      sleep 10; tput cuu1; tput dl1
                   ;;
                   *) 
                   echo -e "$new2" > msg; x=$(wc -l < msg)
                   for i in $(seq $x)
                       do
                     case $i in
                        2|4|6|8|10|12|14|16|18|20)
                              sed -i ""$i"s/^/<code>/" msg; sed -i ""$i"s/$/<\/code>/" msg
                             ;;
                        1|3|5|7|9|11|13|15|17|19)
                              sed -i ""$i"s/^/<b>/" msg; sed -i ""$i"s/$/<\/b>/" msg
                     esac
                   done; msg2=$(<msg)
                   echo -e "\e[01;37mNovos tokens disponíveis | $(cut -d" " -f4 <<< $(date +%T))\e[0m"
                      echo -e "$new2\n==========================================="
                     diff tokens tokens2 -e > dif; echo w >> dif && ed - tokens < dif
                    $(curl -s https://api.telegram.org/$TOKEN/sendMessage -d chat_id="$ID" -d text="$(echo -e "<b>Novos tokens disponíveis | $(cut -d" " -f4 <<< $(date +%T))</b>\n\n$msg2&parse_mode=HTML")" </dev/null >/dev/null 2>&1&)
                    sleep 10
             esac
done
